### ISSUE TITLE
Stunts Not Reset on Catch Your Breath use

### ISSUE THREAD

**Issue by pete284** [waryjack/breathless#9]
First off a good adaptation of the Breathless System it will give me a good way to easily play my own Breathless game "Cargo".

I have only come across one issue, when you Catch Your Breath it correctly resets the skills to the default value, however, if you have used your stunt it does not reset your stunt to unused.

**Comment by philote** [comment]
Thanks, this should be fixed when 0.2.2 rolls out later today
